### ISSUE TITLE
Port multiple route support controls from kaoto

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#81]
### Context
Currently, there's no visual mechanism to handle which route is presented in the canvas

### Goal
The goal of this issue is to port the multiple route controls from `kaoto` into `kaoto-next`. This could be done by leveraging `contextToolbar` property of [`@patternfly/react-topology`](https://www.patternfly.org/topology/toolbar)

### Prerequisites
1. https://github.com/KaotoIO/kaoto-next/issues/136
1. https://github.com/KaotoIO/kaoto-next/issues/137

### Demo
![kaoto-next multiple routes](https://github.com/KaotoIO/kaoto-next/assets/16512618/38b00eaf-bdf4-41b6-a443-ab59947d4f44)

### Todo list
- [ ] Port the multiple route support components to `kaoto-next`
- [ ] Wire up the new route toggle with the `currentDsl` property (Remember to warn the user that the source code will be removed)
- [ ] Wire up the new route button, depending on the `currentDsl` property to add new entities (Some DSL might support multiple routes while others don't)

**Comment by mmelko** [comment]
Due to upcoming possible change in BaseVisualEntities and BaseEntities we agreed that in first shot we will bring
 -  SourceType (Dsl) selector control 
 -  New route button disabled/enabled according the selected SourceType(DSL).

**Comment by lordrip** [comment]
Implemented
